// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJPmNrJZuE1MnREseu9IRVygoVUKS4c94',
    appId: '1:852592456682:web:16681bd37484fec70d3893',
    messagingSenderId: '852592456682',
    projectId: 'final-to-do-list',
    authDomain: 'final-to-do-list.firebaseapp.com',
    storageBucket: 'final-to-do-list.firebasestorage.app',
    measurementId: 'G-D0WD5SPL89',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgMb6da_N4grGsKyEbnXaqKiu2DD1URck',
    appId: '1:852592456682:android:3f5ffa4ba61236100d3893',
    messagingSenderId: '852592456682',
    projectId: 'final-to-do-list',
    storageBucket: 'final-to-do-list.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4qZyjbi18KnTIKGeDFtuwgpnj6OoVaUs',
    appId: '1:852592456682:ios:b6b5c568120f8d180d3893',
    messagingSenderId: '852592456682',
    projectId: 'final-to-do-list',
    storageBucket: 'final-to-do-list.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4qZyjbi18KnTIKGeDFtuwgpnj6OoVaUs',
    appId: '1:852592456682:ios:b6b5c568120f8d180d3893',
    messagingSenderId: '852592456682',
    projectId: 'final-to-do-list',
    storageBucket: 'final-to-do-list.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJPmNrJZuE1MnREseu9IRVygoVUKS4c94',
    appId: '1:852592456682:web:56d2ba9388ea9a250d3893',
    messagingSenderId: '852592456682',
    projectId: 'final-to-do-list',
    authDomain: 'final-to-do-list.firebaseapp.com',
    storageBucket: 'final-to-do-list.firebasestorage.app',
    measurementId: 'G-YCE06MZ8D9',
  );
}
